#!/bin/bash
# show spash screen
DISPLAY=:0 /usr/bin/feh --bg-tile  /home/pi/python_altimeter_pkg/src/gui/resources/splash2.gif
export PYTHONPATH=/home/pi/python_altimeter_pkg/src
cd /home/pi/python_altimeter_pkg/src
DISPLAY=:0 /usr/bin/python gui/main.py
